name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Verify version consistency
        run: |
          # Extract version from pyproject.toml
          PYPROJECT_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")

          # Extract version from git tag (remove 'v' prefix if present)
          GIT_TAG_VERSION=${GITHUB_REF_NAME#v}

          echo "PyProject version: $PYPROJECT_VERSION"
          echo "Git tag version: $GIT_TAG_VERSION"

          # Verify versions match
          if [ "$PYPROJECT_VERSION" != "$GIT_TAG_VERSION" ]; then
            echo "❌ Version mismatch detected!"
            echo "   PyProject.toml version: $PYPROJECT_VERSION"
            echo "   Git tag version: $GIT_TAG_VERSION"
            echo "   Please ensure the version in pyproject.toml matches the release tag."
            exit 1
          fi

          echo "✅ Version consistency verified: $PYPROJECT_VERSION"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: make install

      - name: Run all checks
        run: make check

      - name: Build distribution
        run: make build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
